### ISSUE TITLE
Add student-built remote teaching/IDE platform to resources

### ISSUE THREAD

**Issue by svarlamov** [world-class/REPL#133]
Hi all, member of the first cohort here! I wanted to share a platform that I built for conducting virtual classrooms for teaching coding online that supports Python, JS, TS, Java, and several more popular languages. Posted in the Slack group recently, and wondering which section I should create a PR under this project so that more students and tutors can access this platform. The platform is called Coding Rooms and it's available [here](https://codingrooms.com/). I'd also like to be able to create some kind of offer/code for UoL students and staff to join

**Comment by amenat** [comment]
closed by #134
