### ISSUE TITLE
[BUG] Jekyll site has inconsistent max-width property due to all-contributors section

### ISSUE THREAD

**Issue by amenat** [world-class/REPL#147]
Jekyll site has inconsistent max-width property due to all-contributors section

** Steps to reproduce the behaviour:** 
1. Go to jekyll site https://world-class.github.io/REPL/
2. Scroll down to bottom.
3. Wait till your OCD kicks in.

**Expected behaviour**
Consistent max-width throughout page.

**Screenshots**
![image](https://user-images.githubusercontent.com/9079960/86474404-5fccf880-bd60-11ea-8c0f-8ed70744972a.png)

**Comment by amenat** [comment]
Website looks odd on phone, we need to fix that too 

:soon:

**Comment by sglavoie** [comment]
Yes, again it's not that it's more "broken" than before, but it didn't get fixed either. Still, you came up with the right approach so that's pretty useful in and of itself!

**Comment by sglavoie** [comment]
So, a single-character fix should have solved this issue :tada: : 8001facd80118630db332857ea16173509632913

It looks much better on mobile too. I didn't do any kind of extensive testing for this of course. Let me know what you think: maybe we will be able to close this issue and #148, although that other one could also live on if we plan on actually improving something at some point :smile:.

**Comment by amenat** [comment]
Ah. I should've searched for this config before modifying css :facepalm: 

Anyhoo. Checked recent commit. Now it looks MUCH better and far more readable than before. Especially the detail tags. We can close this one, let other one be open so if someone else wants to contribute better design they can propose :wink:

**Comment by sglavoie** [comment]
> I should've searched for this config before modifying css

No! in fact that was a useful change that you did and at the same time I saw how CSS was supposed to be modified so I ended up making a little change to the `details` tag while I was there. Maybe the `:hover` effect was a bit much, but hey, if it bothers someone else enough, they might just get the necessary motivation to go ahead and fix it by themselves :grin:.
