### ISSUE TITLE
[FEATURE REQUEST] Improve styling CSS of Jekyll generated site

### ISSUE THREAD

**Issue by amenat** [world-class/REPL#148]
title. 

#147 and 87902775f46bcb4b669229e13b7ffb6270219696 are good reference for how to modify CSS. 

Refer theme's code and documentation here: https://github.com/pages-themes/slate/ 

Some suggestions:

- [ ] UoL website like color scheme: https://london.ac.uk ; See how unofficial subreddit handles it perfectly: https://www.reddit.com/r/UniversityOfLondonCS/
- [ ] Improve UI/UX

**Comment by sglavoie** [comment]
Great! Thanks for the links. That would be good to fix this at some point when we might be less busy. :+1: Anyone in that position already can take the lead of course :grin:.

**Comment by sglavoie** [comment]
Oh well, I made some adjustments in the end. Feel free to change whatever you want, I did not do this while wearing a designer hat :slightly_smiling_face:.

**Comment by sglavoie** [comment]
I just saw the suggestions you added. I agree, I think those would be great ideas! I'm all for unifying the experience for fellow students. I like those colors, I think that would work really well and look more professional. I guess that will be a good `v0.13.0` release to contemplate. We gotta make use of this release feature even if the "source code" for this Python/Bash repo is pretty lean and comes with extensive documentation that doesn't even document said source code under the `_assets/` folder :slightly_smiling_face:.

**Comment by sglavoie** [comment]
So, this was not a big change, but does it please the requester? :slightly_smiling_face: 

https://world-class.github.io/REPL/

* It uses some UoL colors as per the hexadecimal values found on the official page: https://london.ac.uk/courses/computer-science
* Not sure the UI/UX was improved :grin:, but what do you reckon should be done about it? A while ago, I talked with @zubmic and we both concluded that a Wiki-style interface would probably be ideal, but unless it's quick and painless to do, that will not be a priority for anyone to fix I guess.

The eternal problems with GitHub is about storing large files and making it harder for contributors not used to Git/GitHub. I would think that using sub-modules is not really approachable for most of the students and any other solution will just complicate things while scattering resources around if we split into multiple repos. It's doable, but should it be done? :smile: 

Maybe https://wiki.js.org/ could be a good open source option (I would prefer something with Python, but arguably using JS on the web is indispensable for now and the goal will probably not be to modify the default software much anyways)? Still, the limiting factor here might be to get sufficient funding to keep it running somewhere like on Heroku. Maybe it could be a good idea to set up a sponsor page. What if someone makes a big enough donation? :grin:

**Comment by sglavoie** [comment]
Well, speaking of funding, I was curious about how GitHub Sponsors work so I set one up, pending approval. :wink:

**Comment by amenat** [comment]
This is exactly what I had in mind. This color-scheme is sort of consistent with other pages (UoL, subreddit)
