### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by osmancalisir** [world-class/REPL#165]
I think the syllabus of CM1035 is not correct. It shows us the ITP1 syllabus. Can you please checkt it?
<br>
https://github.com/world-class/REPL/blob/master/modules/level_4/algorithms_and_data_structures_i/resources/Syllabus_Algorithms_and_Data_Structures_1_CM1035.pdf

**Comment by sglavoie** [comment]
Thank you for reporting this issue! I'm not sure how it managed to switch module like that. Should be fixed and updated in the README now. :+1:

**Comment by sglavoie** [comment]
@all-contributors please add @osmancalisir for bug

**Comment by osmancalisir** [comment]
Thanks for your effort :) 
Best
