### ISSUE TITLE
Adding CM1020 lecture note

### ISSUE THREAD

**Issue by osmancalisir** [world-class/REPL#171]
Hi all,

I wanna add my handwritten discrete mathematics lecture notes from here: 
https://github.com/uolondon/LectureNotes/blob/master/CM1020_Discrete_Mathematics.pdf

Can you please check that?

Best;
Osman

**Comment by sglavoie** [comment]
Hey there :slightly_smiling_face: :wave: 

I've stored your notes here: https://github.com/world-class/binary-assets/tree/master/modules/cm1020_dm/students_notes/osman_calisir

And added them to the DM module here: https://github.com/world-class/REPL/tree/master/modules/level_4/discrete_mathematics#notes

I had to add them to the `binary-assets` repo as we were previously dealing with files that were too big and at nearly 25MB, yours is not a small PDF comparing that to Felipe's notes which are usually under 1MB for any given module with embedded illustrations.

Thanks for sharing in any case, that's really appreciated! :+1: 

@all-contributors please add @osmancalisir for content
