### ISSUE TITLE
Assessment information incorrect for ML

### ISSUE THREAD

**Issue by irfanullahjan** [world-class/REPL#203]
Assessment information for Machine Learning and Neural Networks (CM3015) is incorrect.

On the following page:

https://world-class.github.io/REPL/modules/level-6/cm-3015-machine-learning-neural-networks/#assessment

Under "Assessment", it should say:

"Coursework only (Type II)" instead of "One two-hour unseen written examination and coursework (Type I)"

Source:

Page 35 of Program Regulations

![image](https://user-images.githubusercontent.com/7108679/122658599-a80b4380-d188-11eb-842f-052051609795.png)

**Comment by sglavoie** [comment]
Thank you very much @irfanullahjan for spotting that. That will be an interesting module for sure. Fixed. :slightly_smiling_face: :+1:

**Comment by sglavoie** [comment]
@all-contributors please add @irfanullahjan for bug
