### ISSUE TITLE
[FEATURE REQUEST] Indicate a way to Slack Workspace 🙏 

### ISSUE THREAD

**Issue by yadigarbz** [world-class/REPL#219]
**Is your feature request related to a problem? Please describe.**
I can't find an exact description of joining Slack Workspace. It would be awesome explained

**Describe the solution you'd like**
Adding a proper and clear way for "How to request access to Slack Workspace"

PS: I would like to join to workspace like right now 🙏

**Comment by sglavoie** [comment]
Hi @yadigarbz! The Slack workspace is only available to enrolled students: invitations are sent by the university. Students do not have control over who joins the workspace.

I added some clarifications in #220, I hope that clears things up. That said, I will close the issue as I believe it should be fixed considering the content that's available in the repository.

Please feel free to open more issues if you have further questions. I would encourage you to look at the [Discord server](https://discord.com/invite/zDpffJQ): you can openly join that space and reach out to actual students. Another great option would be to join the [Subreddit](https://www.reddit.com/r/UniversityOfLondonCS/), which is also led by students of this programme.
