### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by osmancalisir** [world-class/REPL#221]
I found these YouTube videos are really useful for Advanced Web Development module. I am currently trying to solve my midterm with following these videos and it seems these videos covers all the requirements. I already prepared the md content. If you think this can be helpful to others as well, happy to see that in the resources :)

- [YouTube](../../../youtube/README.md#advanced-web-development)
    - [Build a Django DRF app and React Front-end - Part-1](https://www.youtube.com/watch?v=soxd_xdHR0o) - Very Academy
    - [Build a Django DRF Quiz API - Part-2](https://www.youtube.com/watch?v=EWJ2-xkfvXI) - Very Academy
    - [JWT Token Authentication with React - Part-3](https://www.youtube.com/watch?v=AfYfvjP1hK8) - Very Academy
    - [Viewsets and Routers with React Front-end Example - Part-4](https://www.youtube.com/watch?v=dCbfOZurCQk) - Very Academy
    - [API Schema and Documentation Generation - Part-5](https://www.youtube.com/watch?v=-nuobfiU49Q) - Very Academy
    - [Filters and Search features - Part-6](https://www.youtube.com/watch?v=3Qdy-FvUEcY) - Very Academy
    - [CRUD with React Front-end - Part-7](https://www.youtube.com/watch?v=Hxadcs7v1NY) - Very Academy
    - [Image Uploading / Handling with React Front-end - Part-8](https://www.youtube.com/watch?v=V2zaeqFSSTE) - Very Academy
    - [Django Rest Framework Course - Social Logins with React and DRF - Part-9](https://www.youtube.com/watch?v=wlcCvzOLL8w) - Very Academy

**Comment by sglavoie** [comment]
Hi @osmancalisir. Thank you for your suggestion. Any pull request will gladly be received, that sounds like a great fit. 😃

**Comment by osmancalisir** [comment]
Hi @sglavoie thanks for your message :)

Sadly, I created a new branch and tried to push it, but it does not allow me to do that. So, I created this issue here :D 

I think, normally, I could send this to a public repo, but do not know what is the reason for now. Can you please do that. You are one of the contributor to this repo, and you can share it, I guess :)

Good luck with your exams, by the way :)

**Comment by sglavoie** [comment]
Thank you @osmancalisir, I've integrated your changes in 6729671. Good luck to you too!
