### ISSUE TITLE
Lecturers name.

### ISSUE THREAD

**Issue by jamda** [world-class/REPL#223]
Hello,
As commented in the #repl I think it could be useful to have the lecturers names when it comes to register for a module.
More lecturers to come and hopefully someone more advanced than me will contribute too.
I thought I would make this first draft PR in case someone disagrees with this idea or the way I presented it in the original README. Please let me know what you think.

_Originally posted by @jamda in https://github.com/world-class/REPL/issues/222#issuecomment-1011261621_

**Comment by ShenZhouHong** [comment]
Thank you for your work, @jamda !
