### ISSUE TITLE
Add more lecturers.

### ISSUE THREAD

**Issue by jamda** [world-class/REPL#225]
Hi there,
Adding more lecturers to lvl5 modules. Will definately need help getting the remaining lvl5 and lvl6 module lecturers. If you could PM (@Txomin) me or something it would be really helpful.

_Originally posted by @jamda in https://github.com/world-class/REPL/issues/224#issuecomment-1011493385_

**Comment by sglavoie** [comment]
Thank you for the initiative @jamda, that's a great idea. 👍 

I'll leave this issue open until it's solved since we're still missing a couple of lecturers.

**Comment by jamda** [comment]
You're welcome! Glad you find it useful @sglavoie .
Sounds good to me.

**Comment by sglavoie** [comment]
@jamda This might be of interest to you 😉. https://github.com/world-class/REPL/commit/ee39e917efee3f30cb9c98981515e62395a26dc4 

Internal Slack reference: https://londoncs.slack.com/archives/CDTPC3FKL/p1613757115260100

**Comment by jamda** [comment]
@sglavoie Thanks alot! That will definately become useful when picking different modules.
