### ISSUE TITLE
How to know I'm eligible for this degree?

### ISSUE THREAD

**Issue by Br-Shihab** [world-class/REPL#227]

**Comment by sglavoie** [comment]
Hi @Br-Shihab,

This is not something students can evaluate. However, you can find the necessary information by doing some preliminary steps:

* Find requirements for admission at [Coursera](https://www.coursera.org/degrees/bachelor-of-science-computer-science-london/admissions).
* The [prospectus](https://london.ac.uk/sites/default/files/prospectuses/bsc-computer-science-prospectus.pdf) has a section on requirements (currently on page 14) that will point you to the [official web page for this degree](https://london.ac.uk/courses/computer-science).
* Better yet, look at the [Programme specifications](https://london.ac.uk/sites/default/files/programme-specifications/progspec-bsc-computer-science.pdf) for more info on the requirements and the [General Regulations](https://london.ac.uk/sites/default/files/regulations/general-regulations-2021-2022.pdf) to know about some requirements and the possibility to do "recognition of prior learning" (there is a section about this in the document).
* Other students have inquired about their eligibility in the [Subreddit](https://www.reddit.com/r/UniversityOfLondonCS/), where you may find inspiration to compare your situation with some other cases.
* You will find additional conversations on this topic and much more at [Discord](https://discord.com/invite/zDpffJQ) where many enrolled students are around to answer questions.

Then, you can also reach out to the university to get a definitive answer:
* If still in doubt before applying, you can contact the university via their [inquiry system](https://sid.london.ac.uk/sid/login/newuserform.aspx?CourseCode=UBS-COSCI-LN&cctc=COMSCI&category=COMSCI).
* Finally, if you've decided you're interested in doing this degree and think you meet the requirements, you can always apply at the [official page for this degreee](https://london.ac.uk/courses/computer-science) (below the section near the top that says "Apply now"), choosing the "standard" route as recommended on that page. If you do not qualify immediately, you might be placed on the performance-based admission instead, which has some initial limitations which you can read about in the documents mentioned above, but most students enter via this route, so nothing to worry about.

Good luck! 👋
