### ISSUE TITLE
Provide source regarding late RPL

### ISSUE THREAD

**Issue by guilhermebpnr** [world-class/REPL#246]
The inclusion of the official source of the following information in the [FAQ page](https://github.com/SergiusGit/REPL/blob/d92d58e2677929b0592f350dacb248592cdf84cb/faq/README.md#can-we-still-apply-rpl-for-google-it-support-course-anytime-during-this-semester-or-next) would be appreciated (as I couldn't find it anywhere 🥴).

> Can we still apply RPL for Google IT Support course anytime during this semester or next
> - You can apply at any time before you take your first level 5 module.

**Comment by sglavoie** [comment]
@guilhermebpnr, are you looking at a fork of this repo, maybe? That information is available word for word in the FAQ: https://github.com/world-class/REPL/tree/master/faq#can-we-still-apply-rpl-for-google-it-support-course-anytime-during-this-semester-or-next

Otherwise, I guess I didn't understand your request. Please feel free to elaborate 🙂.

**Comment by sglavoie** [comment]
I don't think this is mentioned clearly anywhere, but logically speaking, we cannot enroll in modules at level 5 while there are still modules at level 4 that haven't been attempted — the exception being that it is possible to enroll via the normal route (not RPL) to attempt any remaining module(s) at level 4 while selecting the first few modules at level 5.

That would mean that it is not possible to enroll at level 5 while the RPL for Google IT Support hasn't been approved by UoL yet as that would constitute a blocker and you would first need to enroll in the remaining modules at level 4 (i.e., you would need to choose How Computers Work via the non-RPL route to be able to also select modules at level 5).

The progression rules are described in section 5.11 of the [programme regulations](https://www.london.ac.uk/sites/default/files/regulations/progregs-cs-22-23.pdf).

**Comment by sglavoie** [comment]
The above explanations were added to the FAQ in the relevant section. Please feel free to re-open this issue if you find a need to improve these changes further. 😉

**Comment by sglavoie** [comment]
@all-contributors please add @guilhermebpnr for ideas
