### ISSUE TITLE
[BUG] Dead link on a playlist for Discrete Mathematics

### ISSUE THREAD

**Issue by lksmrqrdt** [world-class/REPL#255]
**Describe the bug**

The playlist [Introduction to mathematical thinking](https://www.youtube.com/playlist?list=PL_onPhFCkVQiZgE9U539_QmKLJV_0YvlQ) for the module Discrete Mathematics doesn't exist.  

**To Reproduce**

1. https://github.com/world-class/REPL/tree/master/modules/level-4/cm-1020-discrete-mathematics#supplementary-videos
2. Click on any of the playlists `Introduction to mathematical thinking`.
3. Get the error, that the playlist doesn't exist.

**Expected behavior**

I would expect the playlist containing the relevant videos to be shown.

**Desktop (please complete the following information):**

- OS: macOS Monterey 12.5.1
- Browser: Safari
- Version: 16.0

**Comment by sglavoie** [comment]
Thank you for pointing this out! I've linked to available videos for now, although any PR or issue proposing alternatives will of course be welcome.

@all-contributors please add @lksmrqrdt for bug
