### ISSUE TITLE
[BUG] The mobile layout is broken on the FAQ page

### ISSUE THREAD

**Issue by toxoxi** [world-class/REPL#276]
**Describe the bug**
- The mobile layout is broken on the FAQ page (the screenshot is below)
  - It happens with an environment narrower than 560 widths.
- This issue seems to come from the a-link for the PDF of the intellectual property policy is not wrapped with bullet points.
  - Other long URL links are wrapped with bullet points; therefore fine.

**To Reproduce**

1. Go to https://world-class.github.io/REPL/faq/ using your smartphone or responsive viewer in the developer tool of your browser.
2. The layout should be broken.

**Expected behavior**
- In any width, the issue does not happen.

**Screenshots**

![image](https://github.com/world-class/REPL/assets/29012724/fe0e8859-a5cc-4352-b80c-2ba26a1e6c89)

**Smartphone (please complete the following information):**

- Device: Pixel 6a
- OS: Android
- Browser: chrome
- Version: 114.0.5735.61

**Additional context**
- nothing

**Comment by kaushikpadmanaban** [comment]
Thanks for bringing this to our attention! I was unable to reproduce the error, but I can see that there's a problem with the formatting. I will look into your fix.

**Comment by toxoxi** [comment]
@kaushikpadmanaban 
Thank you for your quick response!

hmm... it still happens with my pixel 6a :(
I also got the same result in the secret mode, so it doesn't seem to be the cache problem.

![Screenshot_20230612-174154.png](https://github.com/world-class/REPL/assets/29012724/46b3428e-954a-4698-8d9b-fba07da77d24)

Should we change the scss?

**Comment by toxoxi** [comment]
I have confirmed that it was solved with the above PR :)
